SELECT DISTINCT LAUNCH_SITE FROM SPACEXTBL;

SELECT LAUNCH_SITE FROM SPACEXTBL 
WHERE LAUNCH_SITE LIKE 'CCA%'
LIMIT 5; 

SELECT SUM(PAYLOAD_MASS__KG_)
FROM SPACEXTBL;

SELECT BOOSTER_VERSION FROM SPACEXTBL;

SELECT AVG(PAYLOAD_MASS__KG_)
FROM SPACEXTBL
WHERE BOOSTER_VERSION = 'F9 v1.1 ';

SELECT DATE
FROM SPACEXTBL
WHERE LANDING__OUTCOME = 'Success (ground pad)'
ORDER BY DATE ASC LIMIT 1;


SELECT UNIQUE BOOSTER_VERSION
FROM SPACEXTBL
WHERE LANDING__OUTCOME = 'Success (drone ship)'
and PAYLOAD_MASS__KG_ BETWEEN 4000 and 6000;

SELECT MISSION_OUTCOME,COUNT(*) 
from SPACEXTBL 
group by MISSION_OUTCOME;

SELECT COUNT(CASE WHEN MISSION_OUTCOME LIKE 'Success%' THEN 1 END) AS Success,
COUNT(CASE WHEN MISSION_OUTCOME LIKE 'Failure%' THEN 1 END) AS Failure
FROM SPACEXTBL;


SELECT BOOSTER_VERSION, LAUNCH_SITE
FROM SPACEXTBL 
WHERE YEAR(DATE)=2015 and LANDING__OUTCOME = 'Failure (drone ship)';













SELECT LANDING__OUTCOME,COUNT(*) 
FROM SPACEXTBL 
WHERE DATE BETWEEN '06-04-2010' AND '03-20-2017'
GROUP BY LANDING__OUTCOME
ORDER BY LANDING__OUTCOME DESC;















SELECT BOOSTER_VERSION
FROM SPACEXTBL
GROUP WHERE PAYLOAD_MASS__KG_ = 15600;
